##################################################################################
#
# Speaking Clock by Marcin Orlowski
#
# @author    Marcin Orlowski <mail@marcinOrlowski.com>
# Copyright  ©2025-2026 Marcin Orlowski <MarcinOrlowski.com>
# @link      https://github.com/MarcinOrlowski/speaking-clock
#
##################################################################################

name: "Markdown Lint"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, dev ]

jobs:
  markdown_lint:
    name: "Markdown linter"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: "Checkout sources"
        uses: actions/checkout@v4

      # https://github.com/marketplace/actions/paths-changes-filter
      - name: "Look for changed doc related files..."
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            docs:
              - '**/*.md'

      # https://github.com/marketplace/actions/my-markdown-linter
      - name: "Running markdown linter..."
        uses: ruzickap/action-my-markdown-linter@v1
        if: steps.filter.outputs.docs == 'true'
        with:
          config_file: .markdownlint.yaml
          # LICENSE is externally sourced and we're not going to fix it.
          exclude: |
            LICENSE.md
